use std::fs;

use crate::error;

const MIT_LICENSE: &str = "MIT License

Copyright (c) 2026 Elysium Team

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the \"Software\"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
";

fn default_manifest(name: &str, version: &str, description: Option<&str>, author: Option<&str>, repository: Option<&str>) -> String {
    let desc = description.map(|s| s.to_string()).unwrap_or_else(|| format!("{} package", name));
    let author = author.map(|s| s.to_string()).unwrap_or_else(|| "Elysium Team".to_string());
    let mut fields = vec![
        format!("  \"name\": \"{}\"", name),
        format!("  \"version\": \"{}\"", version),
        format!("  \"description\": \"{}\"", desc),
        format!("  \"entry\": \"{}.ely\"", name),
        "  \"license\": \"MIT\"".to_string(),
        format!("  \"author\": \"{}\"", author),
    ];
    if let Some(repo) = repository {
        if !repo.is_empty() {
            fields.push(format!("  \"repository\": \"{}\"", repo));
        }
    }
    fields.push("  \"dependencies\": {}".to_string());
    format!("{{\n{}\n}}\n", fields.join(",\n"))
}

fn default_source(name: &str) -> String {
    format!(
        "/// {} package — auto-generated by `elysium init`
///
/// Usage:
///   import \"#/{}\"
///
/// then call any function with {}.functionName()

pub fn hello() -> String {{
  \"Hello from {}!\"
}}
",
        name, name, name, name
    )
}

/// Scaffold a new package directory under `packages/<name>/`.
pub fn cmd_init(
    name: &str,
    description: Option<&str>,
    version: &str,
    author: Option<&str>,
    repository: Option<&str>,
) -> error::Result<()> {
    let cwd = std::env::current_dir()
        .map_err(|e| error::CompileError::new(format!("Cannot get current directory: {}", e)))?;

    let pkg_dir = cwd.join("packages").join(name);

    if pkg_dir.exists() {
        return Err(error::CompileError::new(format!(
            "Package `{}` already exists at {}",
            name,
            pkg_dir.display()
        )));
    }

    // Create the package directory
    fs::create_dir_all(&pkg_dir)
        .map_err(|e| error::CompileError::new(format!("Cannot create {}: {}", pkg_dir.display(), e)))?;

    // Write elysium.json manifest
    let manifest_content = default_manifest(name, version, description, author, repository);
    let manifest_path = pkg_dir.join("elysium.json");
    fs::write(&manifest_path, &manifest_content)
        .map_err(|e| error::CompileError::new(format!("Cannot write {}: {}", manifest_path.display(), e)))?;

    // Write entry source file
    let source_content = default_source(name);
    let source_path = pkg_dir.join(format!("{}.ely", name));
    fs::write(&source_path, &source_content)
        .map_err(|e| error::CompileError::new(format!("Cannot write {}: {}", source_path.display(), e)))?;

    // Write LICENSE
    let license_path = pkg_dir.join("LICENSE");
    fs::write(&license_path, MIT_LICENSE)
        .map_err(|e| error::CompileError::new(format!("Cannot write {}: {}", license_path.display(), e)))?;

    println!("Created package `{}` at {}", name, pkg_dir.display());
    println!("  {}/elysium.json", pkg_dir.display());
    println!("  {}/{}.ely", pkg_dir.display(), name);
    println!("  {}/LICENSE", pkg_dir.display());
    println!();
    println!("Next steps:");
    println!("  - Edit packages/{}/elysium.json to adjust metadata", name);
    println!("  - Write your package source in packages/{}/{}.ely", name, name);
    println!("  - Import it elsewhere with: import \"#/{}\"", name);

    Ok(())
}
