/**
 * Elysium Runtime — Async/Await support module.
 *
 * Provides __await helper for the JS runtime.
 * In the JS backend, `async func` transpiles to `async function`,
 * and `await expr` transpiles to `await expr`, so the runtime
 * support is minimal — mainly a marker/identity function.
 *
 * Usage (generated by compiler):
 *   const __await = require('./async').__await;
 *   let result = await __await(somePromise);
 */

/**
 * __await — wraps a value or promise for the await expression.
 * In v1 this is an identity function. It serves as a marker for
 * the compiler and can be extended to add timeout, cancellation,
 * or promise-pool logic in the future.
 */
function __await(value) {
  // If already a Promise, return as-is for native await.
  // If a plain value, wrap in Promise.resolve for uniform handling.
  if (value instanceof Promise) {
    return value;
  }
  return Promise.resolve(value);
}

/**
 * __async — wraps a function body to ensure it returns a Promise.
 * Used by the compiler when generating async function wrappers.
 */
function __async(fn) {
  return function (...args) {
    try {
      const result = fn.apply(this, args);
      return Promise.resolve(result);
    } catch (err) {
      return Promise.reject(err);
    }
  };
}

module.exports = { __await, __async };
