/**
 * Elysium Runtime — Parallel Blocks support module.
 *
 * Provides __parallel helper for executing statements in parallel.
 * Uses a WorkerPool with real Web Workers (browser: Worker, Node.js: worker_threads)
 * for true parallelism instead of cooperative Promise.all.
 *
 * Usage (generated by compiler):
 *   const __parallel = require('./parallel').__parallel;
 *   __parallel([
 *     () => { stmt1; },
 *     () => { stmt2; },
 *     () => { stmt3; },
 *   ]);
 */

/**
 * WorkerPool — maintains a pool of pre-warmed workers for executing thunks.
 * Each thunk is serialized and sent to a worker for true parallel execution.
 */
class WorkerPool {
  constructor() {
    this.workers = [];
    this.pending = [];
    this.ready = [];
    this.workerCount = this._detectConcurrency();
    this.idCounter = 0;
    this._init();
  }

  _detectConcurrency() {
    if (typeof navigator !== 'undefined' && navigator.hardwareConcurrency) {
      return navigator.hardwareConcurrency;
    }
    if (typeof process !== 'undefined' && process.versions && process.versions.node) {
      try {
        const os = require('os');
        return os.cpus().length;
      } catch (e) {
        return 4;
      }
    }
    return 4;
  }

  _createWorkerBlob() {
    const code = `
      // Worker runtime globals
      self.onmessage = function(e) {
        const task = e.data;
        try {
          const fn = new Function('return (' + task.code + ')')();
          const result = fn();
          self.postMessage({ id: task.id, result: result, error: null });
        } catch (err) {
          self.postMessage({ id: task.id, result: null, error: err.message });
        }
      };
    `;
    if (typeof Blob !== 'undefined' && typeof URL !== 'undefined') {
      const blob = new Blob([code], { type: 'application/javascript' });
      return URL.createObjectURL(blob);
    }
    // Node.js worker_threads uses inline eval, no blob needed
    return null;
  }

  _init() {
    // Determine runtime
    const isNode = typeof process !== 'undefined' && process.versions && process.versions.node;
    const isBrowser = typeof Worker !== 'undefined' && !isNode;

    for (let i = 0; i < this.workerCount; i++) {
      let worker;
      if (isBrowser) {
        const blobUrl = this._createWorkerBlob();
        worker = new Worker(blobUrl);
        worker._url = blobUrl;
      } else {
        try {
          const { Worker: NodeWorker } = require('worker_threads');
          const code = `
            require('worker_threads').parentPort.on('message', (task) => {
              try {
                const fn = new Function('return (' + task.code + ')')();
                const result = fn();
                require('worker_threads').parentPort.postMessage({ id: task.id, result: result, error: null });
              } catch (err) {
                require('worker_threads').parentPort.postMessage({ id: task.id, result: null, error: err.message });
              }
            });
          `;
          worker = new NodeWorker(code, { eval: true });
        } catch (e) {
          worker = null;
        }
      }

      if (worker) {
        worker._busy = false;
        worker._idx = i;
        worker.onmessage = (e) => this._onWorkerMessage(worker, e);
        worker.onerror = (err) => this._onWorkerError(worker, err);
        this.workers.push(worker);
        this.ready.push(worker);
      }
    }

    // Fallback: if no workers could be created, use cooperative scheduling
    if (this.workers.length === 0) {
      this._useFallback = true;
    }
  }

  _onWorkerMessage(worker, e) {
    worker._busy = false;
    const data = e.data || (e.target && e.target.result) || e;
    if (data && data.id !== undefined && this.pending[data.id]) {
      if (data.error) {
        this.pending[data.id].reject(new Error(data.error));
      } else {
        this.pending[data.id].resolve(data.result);
      }
      delete this.pending[data.id];
    }
    this.ready.push(worker);
    this._processQueue();
  }

  _onWorkerError(worker, err) {
    worker._busy = false;
    // Reject all pending tasks for this worker
    const pendingIds = Object.keys(this.pending);
    for (const id of pendingIds) {
      if (this.pending[id]) {
        this.pending[id].reject(new Error(err && err.message ? err.message : 'Worker error'));
        delete this.pending[id];
      }
    }
  }

  _processQueue() {
    if (this._queue && this._queue.length > 0 && this.ready.length > 0) {
      const worker = this.ready.shift();
      const task = this._queue.shift();
      worker._busy = true;
      worker.postMessage({ id: task.id, code: task.code });
    }
  }

  execute(thunk, index) {
    if (this._useFallback) {
      // Cooperative fallback
      return Promise.resolve().then(() => thunk());
    }

    return new Promise((resolve, reject) => {
      const id = this.idCounter++;
      const task = { id, code: thunk.toString(), resolve, reject };

      if (this.ready.length > 0) {
        const worker = this.ready.shift();
        worker._busy = true;
        this.pending[id] = task;
        try {
          worker.postMessage({ id: task.id, code: task.code });
        } catch (e) {
          worker._busy = false;
          this.ready.push(worker);
          reject(e);
        }
      } else {
        // Queue for later
        if (!this._queue) this._queue = [];
        this.pending[id] = task;
        this._queue.push(task);
      }
    });
  }

  terminate() {
    for (const w of this.workers) {
      try { w.terminate(); } catch (e) {}
      if (w._url) {
        try { URL.revokeObjectURL(w._url); } catch (e) {}
      }
    }
    this.workers = [];
    this.ready = [];
    this.pending = [];
    this._queue = [];
  }
}

let _pool = null;

/**
 * __parallel — run an array of thunks in true parallel using WorkerPool.
 * Resolves when all thunks complete.
 *
 * @param {Array<function(): any>} thunks - Array of zero-arg functions
 * @returns {Promise<void>} Resolves when all thunks complete
 */
function __parallel(thunks) {
  if (!Array.isArray(thunks) || thunks.length === 0) {
    return;
  }

  if (!_pool) {
    _pool = new WorkerPool();
  }

  const tasks = thunks.map((thunk, i) => _pool.execute(thunk, i));
  return Promise.all(tasks).then(() => {});
}

module.exports = { __parallel, WorkerPool };
